// <auto-generated />
using System;
using AirCompany.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirCompany.Domain.Migrations
{
    [DbContext(typeof(AirCompanyContext))]
    [Migration("20241212185329_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirCompany.Domain.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision")
                        .HasColumnName("capacity");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision")
                        .HasColumnName("efficiency");

                    b.Property<int>("MaxPassenger")
                        .HasColumnType("integer")
                        .HasColumnName("max_passenger");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.HasKey("Id");

                    b.ToTable("aircrafts");
                });

            modelBuilder.Entity("AirCompany.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_date");

                    b.Property<string>("ArrivalPoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_point");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_point");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("PlaneTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("planetype_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaneTypeId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("AirCompany.Domain.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passport_number");

                    b.HasKey("Id");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("AirCompany.Domain.RegisteredPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BaggageWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("baggage_weight");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer")
                        .HasColumnName("flight_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("registeredPassengers");
                });

            modelBuilder.Entity("AirCompany.Domain.Flight", b =>
                {
                    b.HasOne("AirCompany.Domain.Aircraft", "PlaneType")
                        .WithMany()
                        .HasForeignKey("PlaneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneType");
                });

            modelBuilder.Entity("AirCompany.Domain.RegisteredPassenger", b =>
                {
                    b.HasOne("AirCompany.Domain.Flight", "Flight")
                        .WithMany("Passengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirCompany.Domain.Passenger", "Passenger")
                        .WithMany("RegisteredPassengers")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirCompany.Domain.Flight", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("AirCompany.Domain.Passenger", b =>
                {
                    b.Navigation("RegisteredPassengers");
                });
#pragma warning restore 612, 618
        }
    }
}
